name: Flutter CI

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v5  # Use the latest version
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --web-renderer auto --release